### ISSUE TITLE
Conda package?

### ISSUE THREAD

**Issue by greglucas** [matplotlib/mplcairo#16]
I wasn't able to find a conda install package. I'm wondering if you've considered creating a conda build package for easier installs in addition to pip install? I'm generally on conda environments rather than pipenv's, so this would make that easier for me. I can look into it more if you'd like help with this at all too.

**Comment by anntzer** [comment]
You should be able to just pip-install mplcairo even in a conda environment (in fact this is my normal workflow), if that doesn't work this should be considered a bug.
I personally have little interest in learning how to create conda packages, but if you want to maintain one, go for it.  (See also https://github.com/anntzer/mplcursors/issues/7 for a similar discussion I've had for another of my packages; it resulted in the issue reported creating https://github.com/conda-forge/mplcursors-feedstock which lives its own life now :))

**Comment by greglucas** [comment]
pip-install worked for me no problem (well, almost no problem, it failed first try and required an extra pip install of pkg_config and maybe something else too? I don't have those old logs). The only thing I'd say is that this could maybe help adoption of the package for future use, but I understand your hesitation and comments on the other thread, so no worries!

**Comment by anntzer** [comment]
Again, I will at least try to address pip-related problems.  I cannot do anything about conda-related ones, so I keep away from them.

**Comment by s-m-e** [comment]
@anntzer Bumping this old issue ... I was jumping through the hoops and trying to get [my stuff](https://bewegung.readthedocs.io) packaged [for conda-forge](https://github.com/conda-forge/bewegung-feedstock) when I realized that I could not specify `mplcairo` as a dependency. I understand that you're not interested in packaging `mplcairo` for conda-forge and I also understand why. Would you mind if I give it a try?

**Comment by anntzer** [comment]
Thanks for working on this.
Regarding windows, I will note that while I do build wheels on CI, I have completely disabled the test suite because it systematically crashes on CI (even though the test suite passes fine on local Windows machines).  So it may be OK to skip testing on Windows as well (if the feedstock system does run the test suite).

**Comment by xylar** [comment]
@anntzer, thanks, that's helpful!  My troubles with Windows were actually in building the package, not testing it.  I don't believe we can (or at least want to) build wheels for use by conda-forge but that isn't my area of expertise.  I'll look into it further once we have a feedstock.
