### ISSUE TITLE
Macosx interactive zoom rectangle not updating

### ISSUE THREAD

**Issue by greglucas** [matplotlib/mplcairo#23]
When using the zoom rectangle with the macosx backend, the area highlighted with zoom is not updated immediately. First, it renders itself into the zoomed rectangle, rather than updating the axes. If I then go and adjust the figure window size, that triggers an update of the zoomed region to the full axes. Additionally, in the GUI window it will be showing incorrectly, but if I save the image, the proper image with the zoom is saved. This is presumably because some update/resize_event is triggered on save.

The QT GUI window works as expected. I looked at the code in the QT backend and there is a repaint on every update it looks like. I'm wondering if that logic needs to be propagated into the macosx backend, or if there is an even simpler way to trigger the resize that you can think of. I'm happy to test any ideas out locally if you need as well.

**Comment by anntzer** [comment]
Comparing mplcairo's macos.py and mpl's backend_macosx.py, the first thing that appears may be that at the end of _draw(), just before returning self, one may need to insert a `if self.figure.stale: self.figure.draw(renderer)`?  Right now this is done in a slighly convoluted way (by setting the last_renderer to None and then using ensure_drawn=True), but perhaps there's a race condition somehow?
Does that only appear with zooming?  What about panning?  What if you try to trigger draws manually (e.g. using any of the "interactivity" examples which trigger draws when some button is pressed)?
(I don't have a mac to test.)

**Comment by greglucas** [comment]
Good suggestions! I put that `.figure.stale` check in several places and it didn't help at all. I don't think it is actually in the `draw()` method itself, but rather triggering that update. Panning doesn't work at all actually. Then when I went and tried out the [Slider Demo](https://matplotlib.org/3.1.1/gallery/widgets/slider_demo.html), the canvas is never updated on any of the interactive-ness. So, it is like the events just aren't triggering a redraw, but the events **are** being registered. i.e. in that demo if I click around a bunch and seemingly change parameters the figure never updates. But, if I then go and drag the window to a different frame size all of those previous events get triggered and update the draw properly. I'll try and look into it some more later today, but if any of that triggers an aha, feel free to let me know and I'll test it out for you on a mac.

**Comment by anntzer** [comment]
To be honest with the Matplotlib GSOC start and other real life work I may not have so much time to investigate this in the coming days, but I'll keep it on my TODO and revisit it later if you don't find the fix :-)

**Comment by anntzer** [comment]
0.3 was released on PyPI.

**Comment by greglucas** [comment]
Excellent! 👍 I just installed from the PyPI wheel and everything looks good and interactive figures work for me.
