### ISSUE TITLE
Use MultiPages

### ISSUE THREAD

**Issue by paddy-milo** [matplotlib/mplcairo#27]
I am using matplotlib to plot graphs in an Arch Linux container linked [here](https://hub.docker.com/r/tiagopeixoto/graph-tool). 

I would like to use the MultiPage feature in Cairo but downloading this repo in a container with Arch Linux is complex and I do not want too many dependencies for my container. 

I only need the classes for the MultiPages feature in this repo. I am having trouble doing this.  GraphicsContextRendererCairo is required to define MultiPages but GraphicsContextRendererCairo needs _mplcairo.GraphicsContextRendererCairo. Where can  I find the definition of _mplcairo.GraphicsContextRendererCairo.

**Comment by anntzer** [comment]
It is implemented in C++, so you cannot avoid compiling the extension module and therefore getting all dependencies for doing so.
