### ISSUE TITLE
Demonstrate purpose of this repository with images

### ISSUE THREAD

**Issue by msseibel** [matplotlib/mplcairo#31]
Hello,

I just found your repository and maybe it useful for my problem. [This](https://stackoverflow.com/questions/61400456/avoiding-overlapping-opacities-in-matplotlib) question on stackoverflow lead me here. 

Now I don't know what Cairo is supposed to do. I just found the wikipedia page for Cairo but I don't see how this repository interacts with matplotlib. Moreover I don't have the time to pip install your repo and to run the examples.

Can you demonstrate the capabilities of your repository by adding (linking) some images in the markdown.

Thank you

**Comment by anntzer** [comment]
Thank you for your interest in mplcairo.  Unfortunately I have rather limited bandwidth currently to improve the docs situation, but perhaps you can raise the issue e.g. on the matplotlib discourse forum.

**Comment by msseibel** [comment]
Thank you for the response. 
I will have a look on the discourse forum.
