### ISSUE TITLE
Printing of Tamil language characters

### ISSUE THREAD

**Issue by HitheshSankararaman** [matplotlib/mplcairo#41]
**Output of mplcairo.get_versions()**
{'python': '3.9.12 (main, Jun  1 2022, 11:38:51) \n[GCC 7.5.0]', 'mplcairo': '0.5', 'matplotlib': '3.5.3', 'cairo': '1.16.0', 'freetype': '2.11.0', 'pybind11': '2.10.0', 'raqm': None, 'hb': None}

![c907b492-c814-43e6-8bf4-7657926eff41](https://user-images.githubusercontent.com/67585744/190346681-713d36e0-30c7-4656-9d09-09a58e5d857e.jpg)

The tamil words in x-axis are not printed correctly.
Eg:- சொல்லுங்க
1) Will mplcairo resolve this ?

**Comment by anntzer** [comment]
It will, but you need to also have raqm installed, which is currently not the case (get_versions says 'raqm': None).

**Comment by HitheshSankararaman** [comment]
> It will, but you need to also have raqm installed, which is currently not the case (get_versions says 'raqm': None).

I installed raqm using **sudo apt-get install libraqm-dev** . Still it shows like this . Any pointers ?

**Comment by anntzer** [comment]
What does get_version return?

**Comment by HitheshSankararaman** [comment]
The error got solved . Needed to update,upgrade and restart the machine . Once I did I got the required output. Thank you so much.
