### ISSUE TITLE
Wheels for aarch64

### ISSUE THREAD

**Issue by Sjoerd1993** [matplotlib/mplcairo#47]
Related to issue #46, but since it's a seperate issue I thought I'd file it separately. There's wheels available for x86 on all three major operating systems, and amd64 for Windows.

Is it possible to ship aarch64 wheels as well? Or is this just a lack of a development environment in this architecture that these are not shipped (which is perfectly understandable of course).

**Comment by anntzer** [comment]
I don't have a devenv for this so it's rather low priority personally speaking.  I guess the modern approach would be to switch everything to use cibuildwheel; I'd be willing to consider a PR that does so.

**Comment by Sjoerd1993** [comment]
Thanks, that's completely understandable. Just thought about throwing it out there, as if you did have the environment to quickly build these wheels it would solve some of my headaches. 

If I manage to get a proper modern way to build cross-platfrom wheels I'd submit a PR. But I too have other things on my mind. Again, completely understandable that it's not that high up and it was more of a long shot if that makes sense, I'm closing this issue for now.
